### ISSUE TITLE
I buy markdown plus, but how to show math in ghost

### ISSUE THREAD

**Issue by phpmaple** [tylingsoft/markdown-plus-demo#1]
In markdown plus, i can add
> ```math
E = mc^2
```
or

> ```
sequenceDiagram
  A->>B: How are you?
  B->>A: Great!
```

but I copy and taste In ghost, it not show correct,and how i do?

**Comment by tylerlong** [comment]
I didn't know what is ghost.  I think ghost doesn't support markdown math and diagrams at all.  There is nothing I can do because ghost is not my software.

However, I think ghost does support HTML. Could you just copy and paste the HTML code of the math and diagrams to ghost?
